//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sendingmails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_district_test
    {
        public int sno { get; set; }
        public string District { get; set; }
    }
}
